spring:
  application:
    name: searchservice
  cloud:
      config:
        uri: http://localhost:8090
management:
        security:
          enabled: false
name: Search Service version 1.0
server:
  port: 20193